//var x = 9;
// console.log("hello how are you");
// console.log(x);
// document.write("Hello");
// document.write(x);
// arr = [1, 3, 4];
// console.log(arr);
// document.write(arr);
//window.alert(x);
// document.getElementById("demo").innerHTML="hello";
// document.getElementById("hh").innerHTML=(x*x);
// document.getElementById("hh").innerHTML=Date();
// console.log(Date());
// document.write(Date());
// window.alert(Date());
